### ISSUE TITLE
FinPorts Link

### ISSUE THREAD

**Issue by sangphilkim** [finports/TOOK_Webpages#12]
@kim-yu-ho 
툭 홈페이지에서 핀포츠로 넘어가는 링크가 없어요
풋터에 핀포츠 로고 클릭하면 핀포츠로 넘어가게 링크 걸어주세요~
View More를 클릭하면 핀포츠 네이버 포스트로 넘어가게 해주세요~

**Comment by kim-yu-ho** [comment]
@sangphilkim 
링크 확인했고 스크린 해상도로 구간 할당하여 css 적용했습니다.
